

services:
  postgres:
    image: postgres:15
    container_name: sunuloi_postgres
    restart: always
    environment:
      POSTGRES_USER: legal_app_admin
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: legal_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sunuloi_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: sunuloi_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # désactive la sécurité pour dev
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  backend:
    build: ./legal-app-backend
    container_name: sunuloi_backend
    restart: always
    env_file:
      - ./legal-app-backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    volumes:
      - ./legal-app-backend:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
  elastic_data:
