FROM node:20

# Créer dossier de travail
WORKDIR /app

# Copier package.json et installer les dépendances
COPY package*.json ./
RUN npm install

# Copier tout le code du backend
COPY . .

# Exposer le port de l'API
EXPOSE 5000

# Commande de démarrage
CMD ["node", "server.js"]
